# Generated by Django 4.2.5 on 2023-09-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WPAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField()),
                ("slug", models.SlugField()),
                ("avatar_urls", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="WPCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                ("link", models.URLField()),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("taxonomy", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wpcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="WPTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("count", models.IntegerField(default=0)),
                ("link", models.URLField()),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("taxonomy", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="WPPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("date_gmt", models.DateTimeField()),
                ("guid", models.URLField()),
                ("modified", models.DateTimeField()),
                ("modified_gmt", models.DateTimeField()),
                ("slug", models.SlugField()),
                ("status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("content", models.TextField(blank=True, null=True)),
                ("excerpt", models.TextField(blank=True, null=True)),
                ("comment_status", models.CharField(max_length=255)),
                ("ping_status", models.CharField(max_length=255)),
                ("sticky", models.BooleanField(default=False)),
                ("format", models.CharField(max_length=255)),
                ("template", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wpauthor",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="importer.wpcategory"),
                ),
                ("tags", models.ManyToManyField(blank=True, to="importer.wptag")),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.CreateModel(
            name="WPPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("date_gmt", models.DateTimeField()),
                ("guid", models.URLField()),
                ("modified", models.DateTimeField()),
                ("modified_gmt", models.DateTimeField()),
                ("slug", models.SlugField()),
                ("status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("content", models.TextField(blank=True, null=True)),
                ("excerpt", models.TextField(blank=True, null=True)),
                ("comment_status", models.CharField(max_length=255)),
                ("ping_status", models.CharField(max_length=255)),
                ("sticky", models.BooleanField(default=False)),
                ("template", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wpauthor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wppage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.CreateModel(
            name="WPMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateTimeField()),
                ("date_gmt", models.DateTimeField()),
                ("guid", models.URLField()),
                ("modified", models.DateTimeField()),
                ("modified_gmt", models.DateTimeField()),
                ("slug", models.SlugField()),
                ("status", models.CharField(max_length=255)),
                ("comment_status", models.CharField(max_length=255)),
                ("ping_status", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("template", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("caption", models.TextField()),
                ("alt_text", models.CharField(max_length=255)),
                ("media_type", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=255)),
                ("source_url", models.URLField()),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wpauthor",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importer.wppost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
        migrations.CreateModel(
            name="WPComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wp_id",
                    models.IntegerField(unique=True, verbose_name="Wordpress ID"),
                ),
                ("wp_foreign_keys", models.JSONField(blank=True, null=True)),
                ("wp_many_to_many_keys", models.JSONField(blank=True, null=True)),
                ("wagtail_model", models.JSONField(blank=True, null=True)),
                ("wp_cleaned_content", models.TextField(blank=True, null=True)),
                ("wp_block_content", models.JSONField(blank=True, null=True)),
                ("author_name", models.CharField(max_length=255)),
                ("author_url", models.URLField()),
                ("date", models.DateTimeField()),
                ("date_gmt", models.DateTimeField()),
                ("content", models.TextField(blank=True, null=True)),
                ("link", models.URLField()),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("type", models.CharField(max_length=255)),
                ("author_avatar_urls", models.URLField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="importer.wpauthor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importer.wpcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="importer.wppost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
    ]
