# Generated by Django 4.2.5 on 2023-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpauthor',
            name='avatar_urls',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wpauthor',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
