# Generated by Django 4.2.5 on 2023-09-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_alter_wpauthor_avatar_urls_alter_wpauthor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpauthor',
            name='avatar_urls',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wpauthor',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
