# Generated by Django 4.2.5 on 2023-09-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0005_alter_wpmedia_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpmedia',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
