# Generated by Django 4.2.5 on 2023-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0006_alter_wpmedia_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpcomment',
            name='author_avatar_urls',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wpcomment',
            name='author_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wpcomment',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
