# Generated by Django 4.2.5 on 2023-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0008_alter_wpmedia_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpauthor',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='wpauthor',
            name='slug',
            field=models.SlugField(max_length=500),
        ),
    ]
